# Generated by Django 4.2.7 on 2024-03-19 16:48

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=data.models.skillWrapper, verbose_name='Описание фото'),
        ),
    ]
