# Generated by Django 4.2.7 on 2024-03-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_skill_desc_hardskills_skill_desc_softskills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
