# Generated by Django 4.2.7 on 2023-11-29 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название контакта')),
                ('c_type', models.CharField(choices=[('SIT', 'Сайт'), ('EMA', 'Электронная почта'), ('MAI', 'Древняя почта'), ('PHO', 'Номер'), ('TEL', 'Телеграм'), ('VIB', 'Вайбер'), ('VK', 'Вконтакте'), ('INS', 'Инстаграм'), ('FAC', 'Фейсбук')], max_length=3, verbose_name='Тип контакта')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта (если такой тип)')),
                ('url', models.URLField(blank=True, null=True, verbose_name='УРЛ (если такой тип)')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон (если такой тип)')),
                ('other', models.CharField(blank=True, max_length=255, null=True, verbose_name='Другое (если такой тип)')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='SpecialtyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название группы специальностей')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код')),
                ('g_type', models.CharField(choices=[('S', 'ССО'), ('P', 'ПТО')], max_length=1, verbose_name='Тип')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка')),
                ('prev', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа специальностей',
                'verbose_name_plural': 'Группы специальностей',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код')),
                ('title', models.CharField(max_length=255, verbose_name='Название специальности')),
                ('skill', models.CharField(max_length=255, verbose_name='Название квалификации')),
                ('prev', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specialtygroup', verbose_name='Группа специальностей')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название учреждения образования')),
                ('short_title', models.CharField(max_length=35, verbose_name='Сокращенное название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('schedule', models.TextField(blank=True, null=True, verbose_name='График работы')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Логотип')),
                ('prev', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью')),
                ('promo_medio', models.FileField(blank=True, null=True, upload_to='', verbose_name='Промо ролик')),
                ('coords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Координаты на карте')),
                ('contacts', models.ManyToManyField(to='api.contact', verbose_name='Контакты')),
                ('specialty', models.ManyToManyField(to='api.specialty', verbose_name='Специальности')),
            ],
            options={
                'verbose_name': 'Образовательное учреждение',
                'verbose_name_plural': 'Образовательные учреждения',
            },
        ),
    ]
