# Generated by Django 4.2.7 on 2023-12-05 09:17

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название учреждения образования')),
                ('short_title', models.CharField(max_length=35, verbose_name='Сокращенное название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('schedule', models.TextField(blank=True, null=True, verbose_name='График работы')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('mail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Почтовые реквизиты')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('wsite', models.URLField(blank=True, null=True, verbose_name='Веб сайт')),
                ('wtel', models.URLField(blank=True, null=True, verbose_name='Телеграм')),
                ('wvk', models.URLField(blank=True, null=True, verbose_name='Вк')),
                ('winsta', models.URLField(blank=True, null=True, verbose_name='Инстаграм')),
                ('wother', models.URLField(blank=True, null=True, verbose_name='Прочее')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=api.models.Establishment.wrapper, verbose_name='Логотип')),
                ('prev', models.ImageField(blank=True, null=True, upload_to=api.models.Establishment.wrapper, verbose_name='Превью')),
                ('promo_medio', models.FileField(blank=True, null=True, upload_to=api.models.Establishment.wrapper, verbose_name='Промо ролик')),
                ('coords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Координаты на карте')),
            ],
            options={
                'verbose_name': 'Образовательное учреждение',
                'verbose_name_plural': 'Образовательные учреждения',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.TextField(verbose_name='Вопрос')),
                ('a', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос - Ответ',
                'verbose_name_plural': 'Вопрос - Ответ',
            },
        ),
        migrations.CreateModel(
            name='SpecialtyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название группы специальностей')),
            ],
            options={
                'verbose_name': 'Группа специальностей',
                'verbose_name_plural': 'Группы специальностей',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_type', models.CharField(choices=[('S', 'ССО'), ('P', 'ПТО')], max_length=1, verbose_name='Тип')),
                ('s_type', models.CharField(choices=[('9', 'На основе общего базового образования (после 9 кл.)'), ('11', 'На основе общего среднего образования (после 11 кл.)'), ('PTO', 'На основе ПТО')], max_length=3, verbose_name='На базе ...')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('title', models.CharField(max_length=255, verbose_name='Название специальности')),
                ('skill', models.CharField(max_length=255, verbose_name='Название квалификации')),
                ('prev', models.ImageField(blank=True, null=True, upload_to=api.models.Specialty.wrapper, verbose_name='Превью')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='ИД иконки флаттер')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specialtygroup', verbose_name='Группа специальностей')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=api.models.Gallery.wrapper, verbose_name='Превью')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('est', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.establishment', verbose_name='УО')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_date', models.DateTimeField(verbose_name='Дата мероприятия')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('prev', models.ImageField(blank=True, null=True, upload_to=api.models.Event.wrapper, verbose_name='Превью')),
                ('e_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на страницу мероприятия')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.establishment', verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.AddField(
            model_name='establishment',
            name='specialty',
            field=models.ManyToManyField(to='api.specialty', verbose_name='Специальности'),
        ),
    ]
