# Generated by Django 4.2.7 on 2023-12-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='specialty',
            field=models.ManyToManyField(blank=True, null=True, to='api.specialty', verbose_name='Специальности'),
        ),
    ]
