# Generated by Django 4.2.7 on 2023-11-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='adress',
            field=models.CharField(default='q', max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
