# Generated by Django 4.2.7 on 2023-11-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_specialty_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='c_type',
            field=models.CharField(choices=[('SIT', 'Сайт'), ('EMA', 'Электронная почта'), ('MAI', 'Древняя почта'), ('PHO', 'Номер'), ('TEL', 'Телеграм'), ('VIB', 'Вайбер'), ('VK', 'Вконтакте'), ('INS', 'Инстаграм'), ('FAC', 'Фейсбук')], max_length=10, verbose_name='Тип контакта'),
        ),
    ]
