# Generated by Django 4.2.7 on 2023-11-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_contact_c_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='c_type',
            field=models.CharField(choices=[('SITE', 'Сайт'), ('EMAIL', 'Электронная почта'), ('MAIL', 'Древняя почта'), ('PHONE', 'Номер'), ('TELEGRAM', 'Телеграм'), ('VIBER', 'Вайбер'), ('VK', 'Вконтакте'), ('INST', 'Инстаграм'), ('FACEBOOK', 'Фейсбук')], max_length=10, verbose_name='Тип контакта'),
        ),
    ]
