# Generated by Django 4.2.7 on 2023-12-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=255, verbose_name='Название квалификации')),
                ('s_type', models.CharField(choices=[('9', 'На основе общего базового образования (после 9 кл.)'), ('11', 'На основе общего среднего образования (после 11 кл.)'), ('ПТО', 'На основе ПТО')], max_length=3, verbose_name='На базе ...')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Квалификация',
                'verbose_name_plural': 'Квалификации',
            },
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='s_type',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='skill',
        ),
        migrations.AlterField(
            model_name='specialty',
            name='c_type',
            field=models.CharField(choices=[('ССО', 'ССО'), ('ПТО', 'ПТО')], max_length=3, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Код'),
        ),
    ]
