# Generated by Django 4.2.7 on 2023-12-10 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_skill_s_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.specialty', verbose_name='Специальность'),
            preserve_default=False,
        ),
    ]
