# Generated by Django 4.2.7 on 2023-12-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_skill_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillForEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Сводная таблица',
                'verbose_name_plural': 'Сводная таблица',
            },
        ),
    ]
