# Generated by Django 4.2.7 on 2023-12-11 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_specialty_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.specialty', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='skillforestablishment',
            name='est',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.establishment', verbose_name='УО'),
        ),
        migrations.AlterField(
            model_name='skillforestablishment',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svod', to='api.specialty', verbose_name='Квалификация'),
        ),
    ]
