# Generated by Django 4.2.7 on 2023-12-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_establishment_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='searchtag',
            field=models.TextField(blank=True, null=True, verbose_name='Теги для поиска'),
        ),
    ]
