# Generated by Django 4.2.7 on 2023-12-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_avd_skillforestablishment_b_avd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillforestablishment',
            name='b_avd',
            field=models.FloatField(blank=True, null=True, verbose_name='Средний балл бюджет'),
        ),
    ]
