# Generated by Django 4.2.7 on 2023-12-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_skillforestablishment_b_avd'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillforestablishment',
            name='p_avd',
            field=models.FloatField(blank=True, null=True, verbose_name='Средний балл платное'),
        ),
    ]
