# Generated by Django 4.2.7 on 2024-01-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_skillforestablishment_p_avd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['code'], 'verbose_name': 'Квалификация', 'verbose_name_plural': 'Квалификации'},
        ),
        migrations.RemoveField(
            model_name='skillforestablishment',
            name='skill',
        ),
    ]
